services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs

  amf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-amfd
    restart: on-failure
    privileged: true
    volumes:
      - type: bind
        source: ./config/amf.yaml
        target: /opt/open5gs/etc/open5gs/amf.yaml

  ausf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-ausfd
    restart: on-failure
    privileged: true
    volumes:
      - type: bind
        source: ./config/ausf.yaml
        target: /opt/open5gs/etc/open5gs/ausf.yaml

  bsf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-bsfd
    restart: on-failure
    privileged: true
    volumes:
      - type: bind
        source: ./config/bsf.yaml
        target: /opt/open5gs/etc/open5gs/bsf.yaml

  nrf:
    image: adaptive/open5gs:1.0
    command: open5gs-nrfd
    restart: on-failure
    privileged: true
    volumes:
      - type: bind
        source: ./config/nrf.yaml
        target: /opt/open5gs/etc/open5gs/nrf.yaml

  nssf:
    image: adaptive/open5gs:1.0
    command: open5gs-nssfd
    restart: on-failure
    privileged: true
    volumes:
      - type: bind
        source: ./config/nssf.yaml
        target: /opt/open5gs/etc/open5gs/nssf.yaml

  pcf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-pcfd
    privileged: true
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/pcf.yaml
        target: /opt/open5gs/etc/open5gs/pcf.yaml

  pcrf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-pcrfd
    privileged: true
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/pcrf.yaml
        target: /opt/open5gs/etc/open5gs/pcrf.yaml

  scp:
    image: adaptive/open5gs:1.0
    command: open5gs-scpd
    privileged: true
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/scp.yaml
        target: /opt/open5gs/etc/open5gs/scp.yaml

  smf:
    image: adaptive/open5gs:1.0
    restart: on-failure
    command: open5gs-smfd
    privileged: true
    volumes:
      - type: bind
        source: ./config/smf.yaml
        target: /opt/open5gs/etc/open5gs/smf.yaml

  udm:
    image: adaptive/open5gs:1.0
    restart: on-failure
    command:
    - open5gs-udmd
    privileged: true
    volumes:
      - type: bind
        source: ./config/udm.yaml
        target: /opt/open5gs/etc/open5gs/udm.yaml

  udr:
    image: adaptive/open5gs:1.0
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    privileged: true      
    command:
    - open5gs-udrd
    volumes:
      - type: bind
        source: ./config/udr.yaml
        target: /opt/open5gs/etc/open5gs/udr.yaml

  upf:
    image: adaptive/open5gs:1.0
    command:
    - open5gs-upfd
    cap_add:
    - all
    privileged: true
    restart: on-failure
    # environment:
    # ENABLE_NAT: "false"
    ports:
    - 2152:2152
    volumes:
      - type: bind
        source: ./config/upf.yaml
        target: /opt/open5gs/etc/open5gs/upf.yaml

  webui:
    image: gradiant/open5gs-webui:2.7.0
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
      NODE_ENV: dev
    ports:
    - 9999:9999

  # portainer:
  #   image: portainer/portainer-ce
  #   ports:
  #   - 9000:9000
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
