#!/usr/bin/env python

"""
NetFlux5G - Mininet-WiFi Topology
Generated by NetFlux5G Editor
Generated on: Kam Jul 17 04:54:38 2025
Docker Network: netflux5g

This script creates a network topology using mininet-wifi
with dynamic configuration from the NetFlux5G UI.

5G Configuration Files:
- Located in: ./5g-configs/ directory (relative to this script)
- Contains imported YAML configuration files for 5G core components
- Simplified naming scheme: {component_type}.yaml (e.g., upf.yaml, amf.yaml)
- Multiple instances: {component_type}_{index}.yaml (e.g., upf_2.yaml)
- Volume mounted as: /opt/open5gs/etc/open5gs/{component_type}.yaml inside containers
- Mount these configs into Docker containers as needed

Network Mode Configuration:
- All Docker components (UEs, gNBs, 5G Core) use the universal netflux5g network
- Database, WebUI, Monitoring, and Controller services also use netflux5g network
- Current network mode: netflux5g

Docker Network Usage:
- Network Name: netflux5g
- Type: Bridge network with attachable containers
- Create network: docker network create --driver bridge --attachable netflux5g
- Delete network: docker network rm netflux5g
"""

import sys
import os
from mininet.net import Mininet
from mininet.link import TCLink, Link, Intf
from mininet.node import RemoteController, OVSController, OVSKernelSwitch, Host, Node
from mininet.log import setLogLevel, info
from mn_wifi.node import Station, OVSKernelAP
from mn_wifi.link import wmediumd, Intf
from mn_wifi.wmediumdConnector import interference
from containernet.net import Containernet
from containernet.cli import CLI
from containernet.node import DockerSta
from containernet.term import makeTerm as makeTerm2
from subprocess import call


def sanitize_name(name):
    """Convert display name to valid Python variable name."""
    import re
    # Remove special characters and spaces
    clean_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Ensure it starts with a letter or underscore
    if clean_name and clean_name[0].isdigit():
        clean_name = '_' + clean_name
    return clean_name or 'node'

def get_5g_config_path(component_type, index=1):
    """Get path to 5G configuration file for a component type."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    configs_dir = os.path.join(script_dir, "5g-configs")
    
    # Use simplified naming scheme (0-based internally, 1-based for user)
    comp_type = component_type.lower()
    
    # Convert 1-based user index to 0-based internal index
    internal_index = index - 1
    
    if internal_index == 0:
        # First instance uses simple name: upf.yaml
        config_file = f"{comp_type}.yaml"
    else:
        # Additional instances use numbered names: upf_2.yaml (user index)
        config_file = f"{comp_type}_{index}.yaml"
    
    config_path = os.path.join(configs_dir, config_file)
    
    # Check if file exists, return path regardless
    return config_path

def list_5g_configs():
    """List all available 5G configuration files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    configs_dir = os.path.join(script_dir, "5g-configs")
    
    if os.path.exists(configs_dir):
        import glob
        configs = glob.glob(os.path.join(configs_dir, "*.yaml"))
        configs.extend(glob.glob(os.path.join(configs_dir, "*.yml")))
        return [os.path.basename(c) for c in configs]
    else:
        return []

def check_5g_configs():
    """Check if required 5G configuration files exist and warn about missing files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    configs_dir = os.path.join(script_dir, "5g-configs")
    
    if not os.path.exists(configs_dir):
        print("WARNING: 5g-configs directory not found!")
        print("Run the NetFlux5G automation to copy configuration files.")
        return False
    
    configs = list_5g_configs()
    if configs:
        print(f"Found {len(configs)} 5G configuration files:")
        for config in configs:
            print(f"  - {config}")
        return True
    else:
        print("WARNING: No 5G configuration files found in 5g-configs directory!")
        print("Import configuration files in VGcore component properties first.")
        return False

def check_docker_network():
    """Check if the required Docker network exists."""
    import subprocess
    network_name = "netflux5g"
    try:
        result = subprocess.run(
            ["docker", "network", "ls", "--filter", f"name={network_name}", "--format", "{{.Name}}"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            networks = result.stdout.strip().split('\n')
            return network_name in networks
        return False
    except Exception:
        return False

def create_docker_network_if_needed():
    """Create Docker network if it doesn't exist."""
    import subprocess
    network_name = "netflux5g"
    
    if check_docker_network():
        print(f"Docker network '{network_name}' already exists")
        return True
    
    print(f"Creating Docker network: {network_name}")
    try:
        result = subprocess.run(
            ["docker", "network", "create", "--driver", "bridge", "--attachable", network_name],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            print(f"Successfully created Docker network: {network_name}")
            return True
        else:
            print(f"Failed to create Docker network: {result.stderr}")
            return False
    except Exception as e:
        print(f"Error creating Docker network: {e}")
        return False

def update_hosts(net):
    """
    Add all Mininet/Containernet nodes (hosts, Docker containers, stations)
    to each node's /etc/hosts file for name resolution.
    """
    # Gather all nodes that have a name, IP, and can run commands
    all_nodes = []
    for node in set(list(net.values()) + net.hosts + getattr(net, "stations", [])):
        if hasattr(node, "cmd") and hasattr(node, "name"):
            all_nodes.append(node)

    # Build unique entries: "IP name"
    entries = []
    seen = set()
    for node in all_nodes:
        try:
            ip = node.IP() if callable(getattr(node, "IP", None)) else getattr(node, "ip", None)
            if ip and ip != "127.0.0.1":
                entry = f"{ip} {node.name}"
                if entry not in seen:
                    entries.append(entry)
                    seen.add(entry)
        except Exception:
            continue

    # Update /etc/hosts for all nodes
    for node in all_nodes:
        try:
            node.cmd("sed -i '/# NetFlux5G entries/,/# End NetFlux5G entries/d' /etc/hosts")
            if entries:
                node.cmd("echo '# NetFlux5G entries' >> /etc/hosts")
                for entry in entries:
                    node.cmd(f"echo '{entry}' >> /etc/hosts")
                node.cmd("echo '# End NetFlux5G entries' >> /etc/hosts")
        except Exception:
            continue

export_dir = os.path.dirname(os.path.abspath(__file__))  # Current Working Directory

def topology(args):
    """Create network topology."""
    
    # Check for 5G configuration files
    info("*** Checking 5G configuration files\n")
    check_5g_configs()
    
    # Setup Docker network
    info("*** Setting up universal Docker network\n")
    create_docker_network_if_needed()
    
    # Universal network mode for all NetFlux5G components
    NETWORK_MODE = "netflux5g"
    info(f"*** Using universal Docker network: {NETWORK_MODE}\n")
    
    net = Containernet(topo=None,
                       build=False,
                       link=wmediumd, wmediumd_mode=interference,
                       ipBase='10.0.0.0/8')

    info("*** Adding controller\n")
    Controller__1 = net.addController(name='Controller__1',
                                   controller=RemoteController,
                                   ip='127.0.0.1',
                                   port=6653)

    info("*** Creating nodes\n")
    Switch__6 = net.addSwitch('Switch__6', cls=OVSKernelSwitch, protocols="OpenFlow13")
    Switch__5 = net.addSwitch('Switch__5', cls=OVSKernelSwitch, protocols="OpenFlow13")
    Switch__4 = net.addSwitch('Switch__4', cls=OVSKernelSwitch, protocols="OpenFlow13")
    Switch__3 = net.addSwitch('Switch__3', cls=OVSKernelSwitch, protocols="OpenFlow13")
    Switch__2 = net.addSwitch('Switch__2', cls=OVSKernelSwitch, protocols="OpenFlow13")
    Switch__1 = net.addSwitch('Switch__1', cls=OVSKernelSwitch, protocols="OpenFlow13")

    info("*** Add UPF (2 instances)\n")
    info("    Creating UPF instance 1/2: upf1\n")
    info("      Config file: upf.yaml\n")
    upf1 = net.addDocker('upf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, privileged=True, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/upf.yaml:/opt/open5gs/etc/open5gs/upf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "ENABLE_NAT=true", "NETWORK_INTERFACE=eth0", "OVS_ENABLED=true", "OVS_CONTROLLER=tcp:netflux5g-onos-controller:6653", "OVS_BRIDGE_NAME=br-open5gs", "OVS_FAIL_MODE=secure", "OPENFLOW_PROTOCOLS=OpenFlow13", "OVS_DATAPATH=kernel", "CONTROLLER_PORT=6653", "BRIDGE_PRIORITY=32768", "STP_ENABLED=true"])
    info("    Creating UPF instance 2/2: upf2\n")
    info("      Config file: upf_2.yaml\n")
    upf2 = net.addDocker('upf2', cap_add=["net_admin"], network_mode=NETWORK_MODE, privileged=True, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/upf_2.yaml:/opt/open5gs/etc/open5gs/upf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "ENABLE_NAT=true", "NETWORK_INTERFACE=eth0", "OVS_ENABLED=true", "OVS_CONTROLLER=tcp:netflux5g-onos-controller:6653", "OVS_BRIDGE_NAME=br-open5gs", "OVS_FAIL_MODE=secure", "OPENFLOW_PROTOCOLS=OpenFlow13", "OVS_DATAPATH=kernel", "CONTROLLER_PORT=6653", "BRIDGE_PRIORITY=32768", "STP_ENABLED=true"])
    info("*** Add AMF (1 instances)\n")
    info("    Creating AMF instance 1/1: amf1\n")
    info("      Config file: amf.yaml\n")
    amf1 = net.addDocker('amf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/amf.yaml:/opt/open5gs/etc/open5gs/amf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0", "MCC=999", "MNC=70", "TAC=1", "SST=1", "SD=0xffffff", "OVS_ENABLED=true", "OVS_CONTROLLER=tcp:netflux5g-onos-controller:6653", "OVS_BRIDGE_NAME=br-open5gs", "OVS_FAIL_MODE=secure", "OPENFLOW_PROTOCOLS=OpenFlow13", "OVS_DATAPATH=kernel", "CONTROLLER_PORT=6653", "BRIDGE_PRIORITY=32768", "STP_ENABLED=true"])
    info("*** Add SMF (1 instances)\n")
    info("    Creating SMF instance 1/1: smf1\n")
    info("      Config file: smf.yaml\n")
    smf1 = net.addDocker('smf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/smf.yaml:/opt/open5gs/etc/open5gs/smf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0", "OVS_ENABLED=true", "OVS_CONTROLLER=tcp:netflux5g-onos-controller:6653", "OVS_BRIDGE_NAME=br-open5gs", "OVS_FAIL_MODE=secure", "OPENFLOW_PROTOCOLS=OpenFlow13", "OVS_DATAPATH=kernel", "CONTROLLER_PORT=6653", "BRIDGE_PRIORITY=32768", "STP_ENABLED=true"])
    info("*** Add NRF (1 instances)\n")
    info("    Creating NRF instance 1/1: nrf1\n")
    info("      Config file: nrf.yaml\n")
    nrf1 = net.addDocker('nrf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/nrf.yaml:/opt/open5gs/etc/open5gs/nrf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add SCP (1 instances)\n")
    info("    Creating SCP instance 1/1: scp1\n")
    info("      Config file: scp.yaml\n")
    scp1 = net.addDocker('scp1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/scp.yaml:/opt/open5gs/etc/open5gs/scp.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add AUSF (1 instances)\n")
    info("    Creating AUSF instance 1/1: ausf1\n")
    info("      Config file: ausf.yaml\n")
    ausf1 = net.addDocker('ausf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/ausf.yaml:/opt/open5gs/etc/open5gs/ausf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add BSF (1 instances)\n")
    info("    Creating BSF instance 1/1: bsf1\n")
    info("      Config file: bsf.yaml\n")
    bsf1 = net.addDocker('bsf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/bsf.yaml:/opt/open5gs/etc/open5gs/bsf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add NSSF (1 instances)\n")
    info("    Creating NSSF instance 1/1: nssf1\n")
    info("      Config file: nssf.yaml\n")
    nssf1 = net.addDocker('nssf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/nssf.yaml:/opt/open5gs/etc/open5gs/nssf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add PCF (1 instances)\n")
    info("    Creating PCF instance 1/1: pcf1\n")
    info("      Config file: pcf.yaml\n")
    pcf1 = net.addDocker('pcf1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/pcf.yaml:/opt/open5gs/etc/open5gs/pcf.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add UDM (1 instances)\n")
    info("    Creating UDM instance 1/1: udm1\n")
    info("      Config file: udm.yaml\n")
    udm1 = net.addDocker('udm1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/udm.yaml:/opt/open5gs/etc/open5gs/udm.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])
    info("*** Add UDR (1 instances)\n")
    info("    Creating UDR instance 1/1: udr1\n")
    info("      Config file: udr.yaml\n")
    udr1 = net.addDocker('udr1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/open5gs:latest', position='-538.8,-717.4,0', volumes=[export_dir + "/5g-configs/udr.yaml:/opt/open5gs/etc/open5gs/udr.yaml", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], environment=["DB_URI=mongodb://netflux5g-mongodb/open5gs", "NETWORK_INTERFACE=eth0"])

    info("*** Adding gNB with enhanced OVS/AP support\n")
    GNB__4 = net.addDocker('GNB__4', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, privileged=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=["/lib/modules:/lib/modules:ro", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], position='-515.9,-1153.7,0', txpower=30.0, environment={"AMF_HOSTNAME": "amf1", "GNB_HOSTNAME": "GNB__4", "N2_IFACE": "GNB__4-eth0", "N3_IFACE": "GNB__4-eth0", "RADIO_IFACE": "GNB__4-eth0", "NETWORK_INTERFACE": "eth0", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "UERANSIM_COMPONENT": "gnb", "OVS_ENABLED": "true", "OVS_BRIDGE_NAME": "br-gnb", "OVS_FAIL_MODE": "secure", "OPENFLOW_PROTOCOLS": "OpenFlow13", "OVS_DATAPATH": "kernel", "BRIDGE_PRIORITY": "32764", "STP_ENABLED": "true", "OVS_CONTROLLER": "tcp:netflux5g-onos-controller:6653", "AP_ENABLED": "true", "AP_SSID": "gnb-hotspot4", "AP_CHANNEL": "4", "AP_MODE": "g", "AP_PASSWD": "", "AP_FAILMODE": "secure", "AP_TXPOWER": "30"})
    ap104 = net.addAccessPoint('ap104', cls=OVSKernelAP, ssid='gnb-hotspot4', failMode='secure', datapath='kernel',
                             channel='4', mode='g', position='-515.9,-1153.7,0', txpower=30, protocols="OpenFlow13")

    GNB__3 = net.addDocker('GNB__3', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, privileged=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=["/lib/modules:/lib/modules:ro", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], position='960.6,-1073.1,0', txpower=30.0, environment={"AMF_HOSTNAME": "amf1", "GNB_HOSTNAME": "GNB__3", "N2_IFACE": "GNB__3-eth0", "N3_IFACE": "GNB__3-eth0", "RADIO_IFACE": "GNB__3-eth0", "NETWORK_INTERFACE": "eth0", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "UERANSIM_COMPONENT": "gnb", "OVS_ENABLED": "true", "OVS_BRIDGE_NAME": "br-gnb", "OVS_FAIL_MODE": "secure", "OPENFLOW_PROTOCOLS": "OpenFlow13", "OVS_DATAPATH": "kernel", "BRIDGE_PRIORITY": "32765", "STP_ENABLED": "true", "OVS_CONTROLLER": "tcp:netflux5g-onos-controller:6653", "AP_ENABLED": "true", "AP_SSID": "gnb-hotspot3", "AP_CHANNEL": "11", "AP_MODE": "g", "AP_PASSWD": "", "AP_FAILMODE": "secure", "AP_TXPOWER": "30"})
    ap103 = net.addAccessPoint('ap103', cls=OVSKernelAP, ssid='gnb-hotspot3', failMode='secure', datapath='kernel',
                             channel='11', mode='g', position='960.6,-1073.1,0', txpower=30, protocols="OpenFlow13")

    GNB__2 = net.addDocker('GNB__2', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, privileged=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=["/lib/modules:/lib/modules:ro", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], position='719.9,213.9,0', txpower=30.0, environment={"AMF_HOSTNAME": "amf1", "GNB_HOSTNAME": "GNB__2", "N2_IFACE": "GNB__2-eth0", "N3_IFACE": "GNB__2-eth0", "RADIO_IFACE": "GNB__2-eth0", "NETWORK_INTERFACE": "eth0", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "UERANSIM_COMPONENT": "gnb", "OVS_ENABLED": "true", "OVS_BRIDGE_NAME": "br-gnb", "OVS_FAIL_MODE": "secure", "OPENFLOW_PROTOCOLS": "OpenFlow13", "OVS_DATAPATH": "kernel", "BRIDGE_PRIORITY": "32766", "STP_ENABLED": "true", "OVS_CONTROLLER": "tcp:netflux5g-onos-controller:6653", "AP_ENABLED": "true", "AP_SSID": "gnb-hotspot2", "AP_CHANNEL": "6", "AP_MODE": "g", "AP_PASSWD": "", "AP_FAILMODE": "secure", "AP_TXPOWER": "30"})
    ap102 = net.addAccessPoint('ap102', cls=OVSKernelAP, ssid='gnb-hotspot2', failMode='secure', datapath='kernel',
                             channel='6', mode='g', position='719.9,213.9,0', txpower=30, protocols="OpenFlow13")

    GNB__1 = net.addDocker('GNB__1', cap_add=["net_admin"], network_mode=NETWORK_MODE, publish_all_ports=True, privileged=True, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=["/lib/modules:/lib/modules:ro", export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], position='-615.5,193.1,0', txpower=30.0, environment={"AMF_HOSTNAME": "amf1", "GNB_HOSTNAME": "GNB__1", "N2_IFACE": "GNB__1-eth0", "N3_IFACE": "GNB__1-eth0", "RADIO_IFACE": "GNB__1-eth0", "NETWORK_INTERFACE": "eth0", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "UERANSIM_COMPONENT": "gnb", "OVS_ENABLED": "true", "OVS_BRIDGE_NAME": "br-gnb", "OVS_FAIL_MODE": "secure", "OPENFLOW_PROTOCOLS": "OpenFlow13", "OVS_DATAPATH": "kernel", "BRIDGE_PRIORITY": "32767", "STP_ENABLED": "true", "OVS_CONTROLLER": "tcp:netflux5g-onos-controller:6653", "AP_ENABLED": "true", "AP_SSID": "gnb-hotspot1", "AP_CHANNEL": "1", "AP_MODE": "g", "AP_PASSWD": "", "AP_FAILMODE": "secure", "AP_TXPOWER": "30"})
    ap101 = net.addAccessPoint('ap101', cls=OVSKernelAP, ssid='gnb-hotspot1', failMode='secure', datapath='kernel',
                             channel='1', mode='g', position='-615.5,193.1,0', txpower=30, protocols="OpenFlow13")


    info("*** Adding enhanced UERANSIM UE hosts\n")
    UE__39 = net.addStation('UE__39', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-836.7,-1548.7,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "web1", "MSISDN": "0000000029", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__39-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__31 = net.addStation('UE__31', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-691.9,-677.8,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "internet", "MSISDN": "0000000006", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__31-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__27 = net.addStation('UE__27', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='563.0,-893.0,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "internet2", "MSISDN": "0000000017", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__27-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__15 = net.addStation('UE__15', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1222.9,60.3,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web1", "MSISDN": "0000000025", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__15-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__12 = net.addStation('UE__12', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='844.4,-293.1,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web1", "MSISDN": "0000000022", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__12-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__9 = net.addStation('UE__9', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-259.5,730.1,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet2", "MSISDN": "0000000014", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__9-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__3 = net.addStation('UE__3', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-933.3,-271.5,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet", "MSISDN": "0000000003", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__3-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__40 = net.addStation('UE__40', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-117.0,-1702.4,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "web1", "MSISDN": "0000000030", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__40-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__38 = net.addStation('UE__38', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-42.6,-1484.3,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "web1", "MSISDN": "0000000028", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__38-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__37 = net.addStation('UE__37', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-468.2,-1580.1,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "web1", "MSISDN": "0000000027", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__37-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__36 = net.addStation('UE__36', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-166.1,-990.1,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "web1", "MSISDN": "0000000026", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__36-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__35 = net.addStation('UE__35', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='163.6,-1154.4,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "internet", "MSISDN": "0000000010", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__35-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__34 = net.addStation('UE__34', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-324.5,-1407.2,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "internet", "MSISDN": "0000000009", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__34-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__33 = net.addStation('UE__33', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-872.5,-973.6,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "internet", "MSISDN": "0000000008", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__33-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__32 = net.addStation('UE__32', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-771.4,-1290.1,0', environment={"GNB_HOSTNAME": "GNB__4", "APN": "internet", "MSISDN": "0000000007", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__32-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__30 = net.addStation('UE__30', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='922.9,-1764.9,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "internet2", "MSISDN": "0000000020", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__30-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__29 = net.addStation('UE__29', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1457.2,-1598.3,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "internet2", "MSISDN": "0000000019", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__29-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__28 = net.addStation('UE__28', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1219.0,-994.6,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "internet2", "MSISDN": "0000000018", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__28-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__26 = net.addStation('UE__26', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='660.0,-1494.5,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "internet2", "MSISDN": "0000000016", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__26-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__25 = net.addStation('UE__25', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1448.0,-962.2,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "web1", "MSISDN": "0000000030", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__25-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__24 = net.addStation('UE__24', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1091.8,-763.3,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "web1", "MSISDN": "0000000029", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__24-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__23 = net.addStation('UE__23', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1491.9,-1385.5,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "web1", "MSISDN": "0000000028", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__23-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__22 = net.addStation('UE__22', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1086.4,-1528.2,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "web1", "MSISDN": "0000000027", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__22-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__21 = net.addStation('UE__21', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='594.9,-1225.1,0', environment={"GNB_HOSTNAME": "GNB__3", "APN": "web1", "MSISDN": "0000000026", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__21-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__20 = net.addStation('UE__20', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='427.9,192.0,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web2", "MSISDN": "0000000035", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__20-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__19 = net.addStation('UE__19', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='689.3,825.8,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web2", "MSISDN": "0000000034", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__19-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__18 = net.addStation('UE__18', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1084.8,508.9,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web2", "MSISDN": "0000000033", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__18-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__17 = net.addStation('UE__17', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='569.0,631.5,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web2", "MSISDN": "0000000032", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__17-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__16 = net.addStation('UE__16', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='388.6,541.3,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web2", "MSISDN": "0000000031", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__16-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__14 = net.addStation('UE__14', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='1026.7,123.2,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web1", "MSISDN": "0000000024", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__14-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__13 = net.addStation('UE__13', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='183.6,123.4,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web1", "MSISDN": "0000000023", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__13-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__11 = net.addStation('UE__11', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='356.2,-122.6,0', environment={"GNB_HOSTNAME": "GNB__2", "APN": "web1", "MSISDN": "0000000021", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__11-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__10 = net.addStation('UE__10', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-811.9,675.4,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet2", "MSISDN": "0000000015", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__10-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__8 = net.addStation('UE__8', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-263.7,564.4,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet2", "MSISDN": "0000000013", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__8-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__7 = net.addStation('UE__7', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-183.5,-138.1,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet2", "MSISDN": "0000000012", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__7-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__6 = net.addStation('UE__6', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-749.4,-81.0,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet2", "MSISDN": "0000000011", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__6-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__5 = net.addStation('UE__5', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-994.6,511.2,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet", "MSISDN": "0000000005", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__5-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__4 = net.addStation('UE__4', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-246.2,28.0,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet", "MSISDN": "0000000004", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__4-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__2 = net.addStation('UE__2', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-545.9,700.9,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet", "MSISDN": "0000000002", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__2-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})
    UE__1 = net.addStation('UE__1', devices=["/dev/net/tun"], cap_add=["net_admin"], network_mode=NETWORK_MODE, dcmd="/bin/bash", cls=DockerSta, dimage='adaptive/ueransim:latest', volumes=[export_dir + "/log/:/logging/", os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(export_dir))), "automation", "webshark") + "/captures/:/captures/"], txpower=20.0, position='-1154.2,196.6,0', environment={"GNB_HOSTNAME": "GNB__1", "APN": "internet", "MSISDN": "0000000001", "MCC": "999", "MNC": "70", "SST": "1", "SD": "0xffffff", "TAC": "1", "KEY": "465B5CE8B199B49FAA5F0A2EE238A6BC", "OP_TYPE": "OPC", "OP": "E8ED289DEBA952E4283B54E88E6183CA", "IMEI": "356938035643803", "IMEISV": "4370816125816151", "TUNNEL_IFACE": "uesimtun0", "RADIO_IFACE": "UE__1-wlan0", "SESSION_TYPE": "IPv4", "PDU_SESSIONS": "1", "MOBILITY_ENABLED": "false", "UERANSIM_COMPONENT": "ue", "OVS_ENABLED": "false"})


    info("*** Connecting Docker nodes to APs\n")
    # Dynamic UE-to-gNB/AP connection based on canvas positioning and coverage
    # Dynamic UE assignment to access points (traditional APs and gNB-APs) based on distance and coverage
    # Finding best access point for UE__39 at position (-836.7, -1548.7)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=509.0m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1859.2m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=2351.6m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1755.8m, range=300.0m
    # UE__39 -> GNB #4 (SSID: gnb-hotspot4, distance: 509.0m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__31 at position (-691.9, -677.8)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=507.3m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1699.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1669.8m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=874.3m, range=300.0m
    # UE__31 -> GNB #4 (SSID: gnb-hotspot4, distance: 507.3m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__27 at position (563.0, -893.0)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1109.9m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=436.5m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1118.0m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1602.6m, range=300.0m
    # UE__27 -> GNB #3 (SSID: gnb-hotspot3, distance: 436.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__15 at position (1222.9, 60.3)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2120.6m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1163.4m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=525.9m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1843.2m, range=300.0m
    # UE__15 -> GNB #2 (SSID: gnb-hotspot2, distance: 525.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__12 at position (844.4, -293.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1609.7m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=788.6m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=522.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1538.7m, range=300.0m
    # UE__12 -> GNB #2 (SSID: gnb-hotspot2, distance: 522.1m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__9 at position (-259.5, 730.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1901.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2177.2m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1107.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=644.3m, range=300.0m
    # UE__9 -> GNB #1 (SSID: gnb-hotspot1, distance: 644.3m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__3 at position (-933.3, -271.5)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=975.9m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2056.5m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1723.0m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=562.9m, range=300.0m
    # UE__3 -> GNB #1 (SSID: gnb-hotspot1, distance: 562.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__40 at position (-117.0, -1702.4)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=678.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1247.9m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=2091.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1959.9m, range=300.0m
    # UE__40 -> GNB #4 (SSID: gnb-hotspot4, distance: 678.4m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__38 at position (-42.6, -1484.3)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=577.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1084.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1861.5m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1772.5m, range=300.0m
    # UE__38 -> GNB #4 (SSID: gnb-hotspot4, distance: 577.4m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__37 at position (-468.2, -1580.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=429.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1516.0m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=2151.7m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1779.3m, range=300.0m
    # UE__37 -> GNB #4 (SSID: gnb-hotspot4, distance: 429.1m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__36 at position (-166.1, -990.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=386.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1129.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1494.8m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1265.6m, range=300.0m
    # UE__36 -> GNB #4 (SSID: gnb-hotspot4, distance: 386.1m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__35 at position (163.6, -1154.4)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=679.5m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=801.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1477.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1556.6m, range=300.0m
    # UE__35 -> GNB #4 (SSID: gnb-hotspot4, distance: 679.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__34 at position (-324.5, -1407.2)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=317.6m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1327.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1928.4m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1626.5m, range=300.0m
    # UE__34 -> GNB #4 (SSID: gnb-hotspot4, distance: 317.6m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__33 at position (-872.5, -973.6)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=399.5m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1835.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1986.4m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1194.6m, range=300.0m
    # UE__33 -> GNB #4 (SSID: gnb-hotspot4, distance: 399.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__32 at position (-771.4, -1290.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=289.7m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1745.5m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=2118.0m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1491.4m, range=300.0m
    # UE__32 -> GNB #4 (SSID: gnb-hotspot4, distance: 289.7m)
    # Finding best access point for UE__30 at position (922.9, -1764.9)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1563.2m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=692.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1989.2m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2490.0m, range=300.0m
    # UE__30 -> GNB #3 (SSID: gnb-hotspot3, distance: 692.8m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__29 at position (1457.2, -1598.3)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2022.6m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=722.9m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1956.5m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2739.6m, range=300.0m
    # UE__29 -> GNB #3 (SSID: gnb-hotspot3, distance: 722.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__28 at position (1219.0, -994.6)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1742.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=270.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1307.5m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2185.4m, range=300.0m
    # UE__28 -> GNB #3 (SSID: gnb-hotspot3, distance: 270.1m)
    # Finding best access point for UE__26 at position (660.0, -1494.5)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1224.3m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=517.6m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1709.4m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2115.4m, range=300.0m
    # UE__26 -> GNB #3 (SSID: gnb-hotspot3, distance: 517.6m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__25 at position (1448.0, -962.2)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1973.2m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=499.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1383.3m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2364.9m, range=300.0m
    # UE__25 -> GNB #3 (SSID: gnb-hotspot3, distance: 499.8m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__24 at position (1091.8, -763.3)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1654.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=336.4m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1045.6m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1956.9m, range=300.0m
    # UE__24 -> GNB #3 (SSID: gnb-hotspot3, distance: 336.4m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__23 at position (1491.9, -1385.5)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2021.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=616.4m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1776.0m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2633.1m, range=300.0m
    # UE__23 -> GNB #3 (SSID: gnb-hotspot3, distance: 616.4m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__22 at position (1086.4, -1528.2)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1645.5m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=472.2m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1780.3m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=2420.6m, range=300.0m
    # UE__22 -> GNB #3 (SSID: gnb-hotspot3, distance: 472.2m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__21 at position (594.9, -1225.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1113.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=396.0m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1444.4m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1864.5m, range=300.0m
    # UE__21 -> GNB #3 (SSID: gnb-hotspot3, distance: 396.0m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__20 at position (427.9, 192.0)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1643.6m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1372.7m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=292.8m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1043.4m, range=300.0m
    # UE__20 -> GNB #2 (SSID: gnb-hotspot2, distance: 292.8m)
    # Finding best access point for UE__19 at position (689.3, 825.8)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2317.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1918.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=612.6m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1450.1m, range=300.0m
    # UE__19 -> GNB #2 (SSID: gnb-hotspot2, distance: 612.6m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__18 at position (1084.8, 508.9)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2307.9m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1586.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=469.2m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1729.4m, range=300.0m
    # UE__18 -> GNB #2 (SSID: gnb-hotspot2, distance: 469.2m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__17 at position (569.0, 631.5)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2088.9m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1749.0m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=444.0m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1263.0m, range=300.0m
    # UE__17 -> GNB #2 (SSID: gnb-hotspot2, distance: 444.0m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__16 at position (388.6, 541.3)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1921.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1712.7m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=465.7m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1062.7m, range=300.0m
    # UE__16 -> GNB #2 (SSID: gnb-hotspot2, distance: 465.7m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__14 at position (1026.7, 123.2)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=2002.5m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1198.1m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=319.9m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1643.7m, range=300.0m
    # UE__14 -> GNB #2 (SSID: gnb-hotspot2, distance: 319.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__13 at position (183.6, 123.4)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1456.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1426.7m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=543.9m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=802.1m, range=300.0m
    # UE__13 -> GNB #2 (SSID: gnb-hotspot2, distance: 543.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__11 at position (356.2, -122.6)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1350.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1126.4m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=495.5m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=1021.7m, range=300.0m
    # UE__11 -> GNB #2 (SSID: gnb-hotspot2, distance: 495.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__10 at position (-811.9, 675.4)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1852.9m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2489.8m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1599.8m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=520.8m, range=300.0m
    # UE__10 -> GNB #1 (SSID: gnb-hotspot1, distance: 520.8m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__8 at position (-263.7, 564.4)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1736.4m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2044.6m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1044.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=511.5m, range=300.0m
    # UE__8 -> GNB #1 (SSID: gnb-hotspot1, distance: 511.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__7 at position (-183.5, -138.1)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1068.6m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1477.6m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=969.6m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=544.3m, range=300.0m
    # UE__7 -> GNB #1 (SSID: gnb-hotspot1, distance: 544.3m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__6 at position (-749.4, -81.0)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1097.8m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1977.0m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1498.6m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=305.0m, range=300.0m
    # UE__6 -> GNB #1 (SSID: gnb-hotspot1, distance: 305.0m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__5 at position (-994.6, 511.2)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1732.3m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2516.5m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1740.1m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=494.9m, range=300.0m
    # UE__5 -> GNB #1 (SSID: gnb-hotspot1, distance: 494.9m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__4 at position (-246.2, 28.0)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1212.1m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=1633.6m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=983.8m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=404.5m, range=300.0m
    # UE__4 -> GNB #1 (SSID: gnb-hotspot1, distance: 404.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__2 at position (-545.9, 700.9)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1854.8m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2327.3m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1356.2m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=512.5m, range=300.0m
    # UE__2 -> GNB #1 (SSID: gnb-hotspot1, distance: 512.5m) [OUT OF RANGE - connecting to closest]
    # Finding best access point for UE__1 at position (-1154.2, 196.6)
    # GNB #4 (GNB) at (-515.9, -1153.7): distance=1493.5m, range=300.0m
    # GNB #3 (GNB) at (960.6, -1073.1): distance=2466.7m, range=300.0m
    # GNB #2 (GNB) at (719.9, 213.9): distance=1874.2m, range=300.0m
    # GNB #1 (GNB) at (-615.5, 193.1): distance=538.8m, range=300.0m
    # UE__1 -> GNB #1 (SSID: gnb-hotspot1, distance: 538.8m) [OUT OF RANGE - connecting to closest]

    UE__39.cmd("iw dev UE__39-wlan0 connect gnb-hotspot4")
    UE__31.cmd("iw dev UE__31-wlan0 connect gnb-hotspot4")
    UE__27.cmd("iw dev UE__27-wlan0 connect gnb-hotspot3")
    UE__15.cmd("iw dev UE__15-wlan0 connect gnb-hotspot2")
    UE__12.cmd("iw dev UE__12-wlan0 connect gnb-hotspot2")
    UE__9.cmd("iw dev UE__9-wlan0 connect gnb-hotspot1")
    UE__3.cmd("iw dev UE__3-wlan0 connect gnb-hotspot1")
    UE__40.cmd("iw dev UE__40-wlan0 connect gnb-hotspot4")
    UE__38.cmd("iw dev UE__38-wlan0 connect gnb-hotspot4")
    UE__37.cmd("iw dev UE__37-wlan0 connect gnb-hotspot4")
    UE__36.cmd("iw dev UE__36-wlan0 connect gnb-hotspot4")
    UE__35.cmd("iw dev UE__35-wlan0 connect gnb-hotspot4")
    UE__34.cmd("iw dev UE__34-wlan0 connect gnb-hotspot4")
    UE__33.cmd("iw dev UE__33-wlan0 connect gnb-hotspot4")
    UE__32.cmd("iw dev UE__32-wlan0 connect gnb-hotspot4")
    UE__30.cmd("iw dev UE__30-wlan0 connect gnb-hotspot3")
    UE__29.cmd("iw dev UE__29-wlan0 connect gnb-hotspot3")
    UE__28.cmd("iw dev UE__28-wlan0 connect gnb-hotspot3")
    UE__26.cmd("iw dev UE__26-wlan0 connect gnb-hotspot3")
    UE__25.cmd("iw dev UE__25-wlan0 connect gnb-hotspot3")
    UE__24.cmd("iw dev UE__24-wlan0 connect gnb-hotspot3")
    UE__23.cmd("iw dev UE__23-wlan0 connect gnb-hotspot3")
    UE__22.cmd("iw dev UE__22-wlan0 connect gnb-hotspot3")
    UE__21.cmd("iw dev UE__21-wlan0 connect gnb-hotspot3")
    UE__20.cmd("iw dev UE__20-wlan0 connect gnb-hotspot2")
    UE__19.cmd("iw dev UE__19-wlan0 connect gnb-hotspot2")
    UE__18.cmd("iw dev UE__18-wlan0 connect gnb-hotspot2")
    UE__17.cmd("iw dev UE__17-wlan0 connect gnb-hotspot2")
    UE__16.cmd("iw dev UE__16-wlan0 connect gnb-hotspot2")
    UE__14.cmd("iw dev UE__14-wlan0 connect gnb-hotspot2")
    UE__13.cmd("iw dev UE__13-wlan0 connect gnb-hotspot2")
    UE__11.cmd("iw dev UE__11-wlan0 connect gnb-hotspot2")
    UE__10.cmd("iw dev UE__10-wlan0 connect gnb-hotspot1")
    UE__8.cmd("iw dev UE__8-wlan0 connect gnb-hotspot1")
    UE__7.cmd("iw dev UE__7-wlan0 connect gnb-hotspot1")
    UE__6.cmd("iw dev UE__6-wlan0 connect gnb-hotspot1")
    UE__5.cmd("iw dev UE__5-wlan0 connect gnb-hotspot1")
    UE__4.cmd("iw dev UE__4-wlan0 connect gnb-hotspot1")
    UE__2.cmd("iw dev UE__2-wlan0 connect gnb-hotspot1")
    UE__1.cmd("iw dev UE__1-wlan0 connect gnb-hotspot1")

    info("*** Configuring propagation model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring nodes\n")
    net.configureWifiNodes()

    info("*** Creating links\n")
    # Link APs to gNBs
    net.addLink(ap104, GNB__4)
    net.addLink(ap103, GNB__3)
    net.addLink(ap102, GNB__2)
    net.addLink(ap101, GNB__1)
    
    net.addLink(Switch__5, ap104)
    net.addLink(Switch__6, ap103)
    net.addLink(Switch__2, ap102)
    net.addLink(Switch__3, ap101)
    net.addLink(Switch__1, Switch__6)
    net.addLink(Switch__6, Switch__2)
    net.addLink(Switch__5, Switch__6)
    net.addLink(Switch__5, Switch__2)
    net.addLink(Switch__4, Switch__5)
    net.addLink(Switch__4, amf1)
    net.addLink(Switch__4, upf1)
    net.addLink(Switch__4, upf2)
    net.addLink(Switch__4, smf1)
    net.addLink(Switch__3, amf1)
    net.addLink(Switch__3, upf1)
    net.addLink(Switch__3, upf2)
    net.addLink(Switch__3, smf1)
    net.addLink(Switch__3, Switch__4)
    net.addLink(Switch__1, Switch__3)
    net.addLink(Switch__4, Switch__1)
    net.addLink(Switch__4, Switch__2)
    net.addLink(Switch__1, Switch__2)

    if "-p" not in args:
        net.plotGraph(max_x=1000, max_y=1000)

    info("*** Starting network\n")
    net.build()
    Controller__1.start()

    info("*** Starting APs\n")
    net.get("ap104").start([Controller__1])
    net.get("ap103").start([Controller__1])
    net.get("ap102").start([Controller__1])
    net.get("ap101").start([Controller__1])

    net.get("Switch__6").start([Controller__1])
    net.get("Switch__5").start([Controller__1])
    net.get("Switch__4").start([Controller__1])
    net.get("Switch__3").start([Controller__1])
    net.get("Switch__2").start([Controller__1])
    net.get("Switch__1").start([Controller__1])

    update_hosts(net)

    info("*** Starting UPF components\n")
    upf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-upfd 2>&1 | tee -a /logging/upf1.log  &")
    upf2.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-upfd 2>&1 | tee -a /logging/upf2.log  &")

    info("*** Starting AMF components\n")
    amf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-amfd 2>&1 | tee -a /logging/amf1.log  &")

    info("*** Starting SMF components\n")
    smf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-smfd 2>&1 | tee -a /logging/smf1.log  &")

    info("*** Starting NSSF components\n")
    nssf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-nssfd 2>&1 | tee -a /logging/nssf1.log  &")

    info("*** Starting BSF components\n")
    bsf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-bsfd 2>&1 | tee -a /logging/bsf1.log  &")

    info("*** Starting PCF components\n")
    pcf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-pcfd 2>&1 | tee -a /logging/pcf1.log  &")

    info("*** Starting UDR components\n")
    udr1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-udrd 2>&1 | tee -a /logging/udr1.log  &")

    info("*** Starting UDM components\n")
    udm1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-udmd 2>&1 | tee -a /logging/udm1.log  &")

    info("*** Starting AUSF components\n")
    ausf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-ausfd 2>&1 | tee -a /logging/ausf1.log  &")

    info("*** Starting SCP components\n")
    scp1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-scpd 2>&1 | tee -a /logging/scp1.log  &")

    info("*** Starting NRF components\n")
    nrf1.cmd("setsid nohup /opt/open5gs/etc/open5gs/entrypoint.sh open5gs-nrfd 2>&1 | tee -a /logging/nrf1.log  &")

    CLI.do_sh(net, "sleep 10")

    info("*** Starting enhanced UERANSIM gNB with OVS/AP support\n")
    info("*** Pre-configuring OVS for gNB GNB__4\n")
    # OVS_ENABLED environment variable will trigger setup in entrypoint\n")
    GNB__4.cmd("setsid nohup /entrypoint.sh gnb 2>&1 | tee -a /logging/GNB__4.log &")
    info("*** Pre-configuring OVS for gNB GNB__3\n")
    # OVS_ENABLED environment variable will trigger setup in entrypoint\n")
    GNB__3.cmd("setsid nohup /entrypoint.sh gnb 2>&1 | tee -a /logging/GNB__3.log &")
    info("*** Pre-configuring OVS for gNB GNB__2\n")
    # OVS_ENABLED environment variable will trigger setup in entrypoint\n")
    GNB__2.cmd("setsid nohup /entrypoint.sh gnb 2>&1 | tee -a /logging/GNB__2.log &")
    info("*** Pre-configuring OVS for gNB GNB__1\n")
    # OVS_ENABLED environment variable will trigger setup in entrypoint\n")
    GNB__1.cmd("setsid nohup /entrypoint.sh gnb 2>&1 | tee -a /logging/GNB__1.log &")

    CLI.do_sh(net, "sleep 15")  # Allow time for gNB and OVS setup

    info("*** Starting enhanced UERANSIM UE nodes\n")
    UE__39.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__39.log &")
    UE__31.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__31.log &")
    UE__27.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__27.log &")
    UE__15.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__15.log &")
    UE__12.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__12.log &")
    UE__9.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__9.log &")
    UE__3.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__3.log &")
    UE__40.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__40.log &")
    UE__38.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__38.log &")
    UE__37.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__37.log &")
    UE__36.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__36.log &")
    UE__35.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__35.log &")
    UE__34.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__34.log &")
    UE__33.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__33.log &")
    UE__32.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__32.log &")
    UE__30.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__30.log &")
    UE__29.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__29.log &")
    UE__28.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__28.log &")
    UE__26.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__26.log &")
    UE__25.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__25.log &")
    UE__24.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__24.log &")
    UE__23.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__23.log &")
    UE__22.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__22.log &")
    UE__21.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__21.log &")
    UE__20.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__20.log &")
    UE__19.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__19.log &")
    UE__18.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__18.log &")
    UE__17.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__17.log &")
    UE__16.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__16.log &")
    UE__14.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__14.log &")
    UE__13.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__13.log &")
    UE__11.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__11.log &")
    UE__10.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__10.log &")
    UE__8.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__8.log &")
    UE__7.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__7.log &")
    UE__6.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__6.log &")
    UE__5.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__5.log &")
    UE__4.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__4.log &")
    UE__2.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__2.log &")
    UE__1.cmd("setsid nohup /entrypoint.sh ue 2>&1 | tee -a /logging/UE__1.log &")

    CLI.do_sh(net, "sleep 20")  # Allow time for UE registration and OVS setup

    info("*** Route traffic on UE for End-to-End and End-to-Edge Connection\n")
    UE__39.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__31.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__27.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__15.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__12.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__9.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__3.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__40.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__38.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__37.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__36.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__35.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__34.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__33.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__32.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__30.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__29.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__28.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__26.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__25.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__24.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__23.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__22.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__21.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__20.cmd("ip route add 10.52.0.0/16 dev uesimtun0")
    UE__19.cmd("ip route add 10.52.0.0/16 dev uesimtun0")
    UE__18.cmd("ip route add 10.52.0.0/16 dev uesimtun0")
    UE__17.cmd("ip route add 10.52.0.0/16 dev uesimtun0")
    UE__16.cmd("ip route add 10.52.0.0/16 dev uesimtun0")
    UE__14.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__13.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__11.cmd("ip route add 10.51.0.0/16 dev uesimtun0")
    UE__10.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__8.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__7.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__6.cmd("ip route add 10.200.0.0/16 dev uesimtun0")
    UE__5.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__4.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__2.cmd("ip route add 10.100.0.0/16 dev uesimtun0")
    UE__1.cmd("ip route add 10.100.0.0/16 dev uesimtun0")

    info("*** Checking OVS status for enhanced UERANSIM components\n")
    CLI.do_sh(net, "sleep 5")  # Allow OVS setup to complete\n")
    makeTerm2(GNB__4, cmd="ovs-vsctl show || echo \"OVS not ready for GNB__4\"")
    makeTerm2(GNB__3, cmd="ovs-vsctl show || echo \"OVS not ready for GNB__3\"")
    makeTerm2(GNB__2, cmd="ovs-vsctl show || echo \"OVS not ready for GNB__2\"")
    makeTerm2(GNB__1, cmd="ovs-vsctl show || echo \"OVS not ready for GNB__1\"")

    info("*** Generating maximum load traffic on all UE devices\n")
    Capture2 = export_dir + "/capture-packet-maxload.sh"
    CLI(net, script=Capture2)

    info("*** Running CLI\n")
    CLI(net)

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    topology(sys.argv)
