global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - netflux5g_alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["netflux5g_node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["netflux5g_cadvisor:8080"]

  - job_name: "icmp-probe"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 172.18.0.3 # AMF
          - 172.18.0.9 # PCF
          - 172.18.0.15 # gNB1
          - 172.18.0.17 # UE2
          - 172.25.0.2 # MongoDB
          - 172.25.0.3 # WebUI
          - 8.8.8.8 # Google DNS (contoh eksternal)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: netflux5g_blackbox-exporter:9115

  - job_name: "open5gs-metrics"
    static_configs:
      - targets:
          - "172.18.0.3:9090" # AMF metrics
          - "172.18.0.4:9090" # SMF metrics
          - "172.18.0.5:9090" # UPF metrics
          - "172.18.0.6:9090" # NRF metrics
          - "172.18.0.7:9090" # AUSF metrics
          - "172.18.0.8:9090" # UDM metrics
          - "172.18.0.9:9090" # PCF metrics
          - "172.18.0.10:9090" # UDR metrics
          - "172.18.0.11:9090" # BSF metrics
          - "172.18.0.12:9090" # NSSF metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "ueransim-metrics"
    static_configs:
      - targets:
          - "172.18.0.15:9091" # gNB1 metrics
          - "172.18.0.16:9091" # gNB2 metrics
          - "172.18.0.17:9091" # UE metrics
    scrape_interval: 10s
    scrape_timeout: 5s
