default:
  auth:
    community: public
  version: 2
  retries: 3
  timeout: 10s
  walk:
    - 1.3.6.1.2.1.1
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
      type: gauge
      help: The time (in hundredths of a second) since the network management portion of the system was last re-initialized.
    - name: ifNumber
      oid: 1.3.6.1.2.1.2.1
      type: gauge
      help: The number of network interfaces present on this system.
    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      type: gauge
      help: The size of the largest packet which can be sent/received on the interface, specified in octets.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifSpeed
      oid: 1.3.6.1.2.1.2.2.1.5
      type: gauge
      help: An estimate of the interface's current bandwidth in bits per second.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifAdminStatus
      oid: 1.3.6.1.2.1.2.2.1.7
      type: gauge
      help: The desired state of the interface.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifOperStatus
      oid: 1.3.6.1.2.1.2.2.1.8
      type: gauge
      help: The current operational state of the interface.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifInOctets
      oid: 1.3.6.1.2.1.2.2.1.10
      type: counter
      help: The total number of octets received on the interface.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifOutOctets
      oid: 1.3.6.1.2.1.2.2.1.16
      type: counter
      help: The total number of octets transmitted on the interface.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifInErrors
      oid: 1.3.6.1.2.1.2.2.1.14
      type: counter
      help: The number of inbound packets that contained errors.
      indexes:
        - labelname: ifIndex
          type: gauge
    - name: ifOutErrors
      oid: 1.3.6.1.2.1.2.2.1.20
      type: counter
      help: The number of outbound packets that could not be transmitted because of errors.
      indexes:
        - labelname: ifIndex
          type: gauge
